Code/steve/django/catmob/catbusters/urls.py
from django.urls import path
from .views import home, all, up_vote, down_vote


app_name = 'catbusters'
urlpatterns = [
    path('', home, name='home'),
    path('all/', all, name="all"),
    path('up_vote/<int:cat_id>/', up_vote, name="up_vote"),
    path('down_vote/<int:cat_id>/', down_vote, name="down_vote"),
]

Code/steve/django/catmob/catmob/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catbusters.urls')),
]

Code/steve/django/catmob/catbusters/models.py
from django.db import models

# Create your models here.
class Cat(models.Model):
    url = models.URLField(unique=True)
    up_votes = models.IntegerField(default=0)
    down_votes = models.IntegerField(default=0)
    total_votes = models.IntegerField(default=0)

    def __str__(self):
        return str(self.id)

    def get_total(self):
        return self.up_votes - self.down_votes

Code/steve/django/catmob/catbusters/views.py
from django.http.response import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, reverse
from django.http import HttpResponse
import requests
from .models import Cat


def home(request):
    cat_dict = (requests.get(
        'https://api.thecatapi.com/v1/images/search')).json()[0]

    cat_egories = (requests.get(
        'https://api.thecatapi.com/v1/categories')).json()

    cat_url = cat_dict['url']

    context = {
        'cat_url': cat_url,
        'cat_egories': cat_egories,
    }

    # Save cat_url to database
    cat = Cat()
    cat.url = cat_url
    cat.save()

    return render(request, 'catbusters/index.html', context)


def all(request):
    cats = Cat.objects.all().order_by('-total_votes')

    context = {
        'cats': cats
    }

    return render(request, 'catbusters/all.html', context)

def up_vote(request, cat_id):
    cat = Cat.objects.get(id=cat_id)
    cat.up_votes += 1
    cat.total_votes = cat.get_total()
    cat.save()

    return HttpResponseRedirect(reverse('catbusters:all'))

def down_vote(request, cat_id):
    cat = Cat.objects.get(id=cat_id)
    cat.down_votes += 1
    cat.total_votes = cat.get_total()
    cat.save()

    return HttpResponseRedirect(reverse('catbusters:all'))

Code/steve/django/catmob/catbusters/templates/catbusters/all.html
{% extends 'catbusters/base.html' %}

{% block title %}
CATS
{% endblock %}

{% block content %}
<div class="container">
  <h1>All Cats</h1>

  {% for cat in cats %}
    <div class="cat-image">
      <img src="{{cat.url}}" alt="cat">
      <a href="{% url 'catbusters:up_vote' cat.id %}" class="btn">⬆ {{cat.up_votes}}</a>
      <a href="{% url 'catbusters:down_vote' cat.id %}" class="btn">⬇ {{cat.down_votes}}</a>
      <p>Diff: {{cat.total_votes}}</p>
    </div>
  {% endfor %}

</div>
{% endblock %}

Code/steve/django/catmob/catbusters/templates/catbusters/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'catbusters/style.css' %}">
</head>
<body>
    

    {% block content %}
    {% endblock %}
    

</body>
</html>

Code/steve/django/catmob/catbusters/templates/catbusters/index.html
{% extends 'catbusters/base.html' %}

{% block title %}
CatBusters v 2.0 new and improved with javascript
{% endblock %}

{% block content %}

<header>
<h1>Welcome to CatBusters!</h1>
</header>

<div class="main">
<img id="cat_img" src="{{ cat_url }}" alt="Cat, meow">

<div class="user_input">
<select name="cat_drop" id="cat_select">
    {% for cats in cat_egories %}
    <option value="{{ cats.id }}">{{ cats.name }}</option>
    {% endfor %}
</select>
<button type="submit" onclick="return cat_search()">Generate Cat</button>
</div>

<script type="text/javascript">
function cat_search() {
    let cat_select = document.getElementById('cat_select').value;
    let cat_base = 'https://api.thecatapi.com/v1/images/search?category_ids='
    let cat_url = cat_base + cat_select
    let cat_img = document.getElementById("cat_img")

    fetch(cat_url)
    .then(response => response.json())
    .then(data => cat_img.src = data[0].url)
}
</script>
</div>

{% endblock %}