Code/anthony/django/phonebook/contacts/urls.py
from django.urls import path
from .views import home_page, all_contacts, save_contact, search_contact, contact_details

app_name = "contacts"
urlpatterns = [
    # contacts/
    path("", home_page, name="home"),
    # contacts/all
    path("all/", all_contacts, name="all_contacts"),
    path("save_contact/", save_contact, name="save_contact"),
    path("search/", search_contact, name="search_contact"),
    path("details/<int:contact_id>/", contact_details, name="details")
]

Code/anthony/django/phonebook/contacts/models.py
from django.db import models

# Create your models here.


class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, null=True, blank=True)
    phone_number = models.CharField(max_length=15, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    is_cool = models.BooleanField()

    def full_name(self):
        if self.last_name:
            return f"{self.first_name} {self.last_name}"
        else:
            return f"{self.first_name}"

    def coolness(self):
        if self.is_cool:
            return "cool"
        else:
            return "not cool"

    def __str__(self):
        return f"{self.coolness()} -- {self.full_name()}"

Code/anthony/django/phonebook/contacts/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import Contact


def home_page(request):
    return render(request, 'contacts/index.html')


def all_contacts(request):
    cool_contacts = Contact.objects.filter(is_cool=True).order_by('first_name')

    not_cool_contacts = Contact.objects.filter(
        is_cool=False).order_by('first_name')

    context = {
        "cool_contacts": cool_contacts,
        "not_cool_contacts": not_cool_contacts
    }

    return render(request, 'contacts/all_contacts.html', context)


def save_contact(request):
    print(request.POST)
    # Create a new contact
    contact = Contact()
    # Rename request.POST to form
    form = request.POST

    # Assign contact attributes from form data
    contact.first_name = form['first_name'].title()
    contact.last_name = form['last_name'].title()
    contact.phone_number = form['phone_number']
    contact.email = form['email']
    contact.address = form['address']

    if form.get('is_cool') == 'on':
        contact.is_cool = True
    else:
        contact.is_cool = False

    contact.save()

    return HttpResponseRedirect(reverse('contacts:all_contacts'))


def search_contact(request):
    name = request.POST['first_name']
    if name:  # "Hector"
        contacts = Contact.objects.filter(first_name=name)
    else:
        contacts = ""

    context = {
        'contacts': contacts
    }

    return render(request, 'contacts/search_results.html', context)


def contact_details(request, contact_id):

    contact = Contact.objects.get(id=contact_id)

    context = {
        'contact': contact
    }

    return render(request, 'contacts/details.html', context)

Code/anthony/django/phonebook/contacts/templates/contacts/_footer.html
<footer>
  <div class="copy">CodeBusters &copy; 2021</div>
  <div class="links">
    <a href="">Contact Us</a>
    <a href="">FAQ</a>
    <a href="">Careers</a>
    <a href="">Support</a>
    <a href="">Legal</a>
  </div>
</footer>

Code/anthony/django/phonebook/contacts/templates/contacts/_navbar.html
<nav>
    <a href="{% url 'contacts:home' %}">
      <i class="bi bi-book-half"></i>
    </a>
    <div class="links">
      <a href="{% url 'contacts:home' %}">Home</a>
      <a href="{% url 'contacts:all_contacts' %}">Contacts</a>
      <a href="{% url 'yellowpages:home' %}">Yellow Pages</a>
    </div>
  </nav>

Code/anthony/django/phonebook/contacts/templates/contacts/all_contacts.html
{% extends 'contacts/base.html' %}

{% block title %}
All Contacts
{% endblock %}

{% block content %}
<h1>All Contacts</h1>

<!-- Form to add new contact -->
<form action="{% url 'contacts:save_contact' %}" method="POST">
  {% csrf_token %}
  <input type="text" name="first_name" placeholder="First Name">
  <input type="text" name="last_name" placeholder="Last Name">
  <input type="text" name="phone_number" placeholder="Phone #">
  <input type="text" name="email" placeholder="Email">
  <input type="text" name="address" placeholder="Address">
  <label for="cool">
    Is Cool:
    <input name="is_cool" type="checkbox">
  </label>
  <input type="submit" value="Submit">
</form>

<div class="cool-not-cool">
  <div class="cool">
    <!-- Loop over all contacts -->
    {% for contact in cool_contacts %}
    <div>
      <h2>
        <a href="{% url 'contacts:details' contact.id %}">{{ contact.full_name }} is {{ contact.coolness }}</a>
      </h2>
    </div>
    {% endfor %}
  </div>

  <div class="not-cool">
    {% for contact in not_cool_contacts %}
    <div>
      <h2>
        <a href="{% url 'contacts:details' contact.id %}">{{ contact.full_name }} is {{ contact.coolness }}</a>
      </h2>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

Code/anthony/django/phonebook/contacts/templates/contacts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'contacts/style.css' %}">

  <!-- Bootstrap icons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.5.0/font/bootstrap-icons.min.css" integrity="sha512-xnP2tOaCJnzp2d2IqKFcxuOiVCbuessxM6wuiolT9eeEJCyy0Vhcwa4zQvdrZNVqlqaxXhHqsSV1Ww7T2jSCUQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>

  {% include 'contacts/_navbar.html' %}

  {% block content %}
  {% endblock %}

  {% include 'contacts/_footer.html' %}
</body>
</html>

Code/anthony/django/phonebook/contacts/templates/contacts/details.html
{% extends 'contacts/base.html' %}

{% block title %}
{{ contact.full_name }}
{% endblock %}

{% block content %}
  <h1>Name: {{ contact.full_name }}</h1>
  <p>Email: {{ contact.email }}</p>
  <p>Phone #: {{ contact.phone_number }}</p>
  {% if contact.address %}
  <p>Address: {{ contact.address }}</p>
  {% endif %}
{% endblock %}

Code/anthony/django/phonebook/contacts/templates/contacts/index.html
{% extends 'contacts/base.html' %}

{% block title %}
Contacts
{% endblock %}

{% block content %}
  <h1>Welcome to Contacts!</h1>
  <form action="{% url 'contacts:search_contact' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="first_name" placeholder="Look up by first name">
    <button type="submit">Search</button>
  </form>
{% endblock %}

Code/anthony/django/phonebook/contacts/templates/contacts/search_results.html
{% extends 'contacts/base.html' %}

{% block title %}
Search Results
{% endblock %}

{% block content %}

  {% if contacts %}
    {% for contact in contacts %}
      {{ contact.full_name }} -- {{ contact.coolness }}
    {% endfor %}
  {% else %}
  <h2>No contacts with that name</h2>
  {% endif %}

{% endblock %}