Code/anthony/django/Kintter/Kintter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kats.urls')),
]

Code/anthony/django/Kintter/kats/urls.py
from django.urls import path
from .views import home, get_cat, all_cats, vote_down, vote_up

app_name = "kats"
urlpatterns = [
    path('', home, name="home"),
    path('get_cats/', get_cat, name="get_cat"),
    path('view_all/', all_cats, name="view_all"),
    path('updoot/<int:cat_id>/', vote_up, name="updoot"),
    path('downdoot/<int:cat_id>/', vote_down, name="downdoot"),
]

Code/anthony/django/Kintter/kats/models.py
from django.db import models

# Create your models here.
class Cat(models.Model):
    url = models.URLField(unique=True)
    up_doots = models.IntegerField(default=0)
    down_doots = models.IntegerField(default=0)

    def __str__(self):
        return f"Cat #{self.id}"

    def get_doots(self):
        return self.up_doots - self.down_doots

Code/anthony/django/Kintter/kats/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, reverse
from . import secrets

import requests as fetch

from .models import Cat

# Create your views here.
def home(request):
    # Get Cat categories
    cat_url = 'https://api.thecatapi.com/v1/categories'
    response = fetch.get(cat_url, headers = {'x-api-key': secrets.api_key})
    cat_egories = response.json()

    # Random cat image url
    URL = 'https://api.thecatapi.com/v1/images/search'

    # If category specified in query params, get cat from that category
    if 'category' in request.GET:
        category = request.GET['category']
        valid = False
        for cat in cat_egories:
            if str(cat['id']) == category:
                valid = True
                break
        if valid:
            URL = 'https://api.thecatapi.com/v1/images/search?category_ids=' + category

    # Getting cat image url
    response = fetch.get(URL)
    data = response.json()
    cat_image = data[0]['url']

    cat = Cat(url=cat_image)
    cat.save()


    context = {
        'cat_image': cat_image,
        'cat_egories': cat_egories
    }

    return render(request, 'kats/index.html', context)


def get_cat(request):
    form = request.POST
    category = form['category']

    print(request.META['REMOTE_ADDR'])

    return HttpResponseRedirect(reverse('kats:home') + f'?category={category}')


def all_cats(request):
    cats = Cat.objects.all().order_by('-up_doots')
    context = {
        'cats': cats
    }

    return render(request, 'kats/view_all.html', context)


def vote_up(request, cat_id):
    cat = Cat.objects.get(id=cat_id)
    cat.up_doots += 1
    cat.save()
    return HttpResponseRedirect(reverse('kats:view_all'))

def vote_down(request, cat_id):
    cat = Cat.objects.get(id=cat_id)
    cat.down_doots += 1
    cat.save()
    return HttpResponseRedirect(reverse('kats:view_all'))

Code/anthony/django/Kintter/kats/templates/kats/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Kintter</title>
  <link rel="stylesheet" href="{% static 'kats/style.css' %}">
</head>
<body>
  <form action="{% url 'kats:get_cat' %}" method="POST">
    {% csrf_token %}
    <select name="category">
      <option value="" selected disabled>Select a KATegorie</option>
      {% for cat in cat_egories %}
        <option value="{{cat.id}}">{{cat.name}}</option>
      {% endfor %}
    </select>
    <button type="submit">Random Cat</button>
  </form>
  <img src="{{ cat_image }}" alt="cats">
</body>
</html>

Code/anthony/django/Kintter/kats/templates/kats/view_all.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  {% for cat in cats %}
    <div>
      <img src="{{cat.url}}">
      <div class="doots">
        <a href="{% url 'kats:updoot' cat.id %}">&uparrow; {{cat.up_doots}}</a>
        <a href="{% url 'kats:downdoot' cat.id %}">&downarrow; {{cat.down_doots}}</a>
      </div>
    </div>
  {% endfor %}
</body>
</html>