Code/jesse/django/AskCodeBusters/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.home, name="home"),
    path('vote/<int:choice_id>/', views.vote, name="vote"),
    path('generate_choices/', views.generate_choices, name="generate_choices"),
    path('add_choices/', views.add_choices, name="add_choices"),
    path('signup/', views.signup, name="signup"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name='logout'),
    path('<str:username>/', views.user_polls, name="user_polls"),
]

Code/jesse/django/AskCodeBusters/polls/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


# models.CASCADE = delete
# models.PROTECT = prevent deletion


# Question
class Question(models.Model):
    question_text = models.CharField(max_length=150)
    user = models.ForeignKey(User, on_delete=models.PROTECT, related_name="questions")

    def __str__(self):
        return self.question_text


# Choice
class Choice(models.Model):
    choice_text = models.CharField(max_length=75)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name="choices")

    def __str__(self):
        return self.choice_text

Code/jesse/django/AskCodeBusters/polls/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, reverse
from .models import Question, Choice
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.

def home(request):
    questions = Question.objects.all()
    context = {
        'questions': questions
    }
    return render(request, 'polls/index.html', context)

@login_required
def vote(request, choice_id):
    choice_id = 3 if choice_id == 4 else choice_id
    # choice = Choice.objects.get(id=choice_id)
    choice = get_object_or_404(Choice, id=choice_id)
    choice.votes += 1
    choice.save()
    context = {
        'question': choice.question
    }
    return render(request, 'polls/results.html', context)

@login_required
def generate_choices(request):
    form = request.POST
    text = form['question_text']
    num_choice = form['num_choice']
    
    question = Question()
    question.question_text = text
    question.user = request.user
    question.save()

    num_choice = list(range(int(num_choice)))

    context = {
        'choices': num_choice,
        'question': question
    }

    return render(request, 'polls/choices.html', context)

@login_required
def add_choices(request):
    form = request.POST
    question = get_object_or_404(Question, id=form['question_id'])

    for key in form:
        if key.startswith('choice'):
            new_choice = Choice()
            new_choice.choice_text = form[key]
            new_choice.question = question
            new_choice.save()

    return HttpResponseRedirect(reverse('polls:home'))

def signup(request):
    print('METHOD', request.method)
    if request.method == "GET":
        return render(request, 'polls/signup.html')
    elif request.method == "POST":
        print('FORM', request.POST)

        # Get data from our form
        form = request.POST
        username = form['username']
        password = form['password']
        email = form['email']
        first_name = form['first_name']
        last_name = form['last_name']
        # Create user. username, email, password order matters
        user = User.objects.create_user(
            username, email, password, first_name=first_name, last_name=last_name
            )

        login(request, user)

        return HttpResponseRedirect(reverse('polls:home'))

def login_user(request):
    # User visits page
    if request.method == "GET":
        return render(request, 'polls/login.html')
    # User submits form
    elif request.method =="POST":
        print('FORM', request.POST)
        # Get form data
        form = request.POST
        username = form['username']
        password = form['password']

        # Authenticate User
        user = authenticate(request, username=username, password=password)
        if user != None:
            login(request, user)
        
        return HttpResponseRedirect(reverse('polls:home'))
    
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('polls:home'))

def user_polls(request, username):

    user = get_object_or_404(User, username=username)

    context = {
        'user': user
    }
    return render(request, 'polls/user_polls.html', context)

Code/jesse/django/AskCodeBusters/polls/templates/polls/_navbar.html
<nav>
  <h1><a href="{% url 'polls:home' %}">AskCodeBusters</a></h1>
  <div>
    {% if request.user.is_anonymous %}
    <a href="{% url 'polls:signup' %}">Sign Up</a>
    <a href="{% url 'polls:login' %}">Login</a>
    {% else %}
    <a href="{% url 'polls:logout' %}">Logout</a>
    {% endif %}
  </div>
</nav>

Code/jesse/django/AskCodeBusters/polls/templates/polls/choices.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{question.question_text}}</title>
</head>
<body>
  {% include 'polls/_navbar.html' %}
  <h1>{{question.question_text}}</h1>
  <form action="{% url 'polls:add_choices' %}" method="POST">
    {% csrf_token %}
    {% for x in choices %}
    <input type="text" name="choice{{forloop.counter}}" placeholder="Choice {{forloop.counter}}">
    {% endfor %}
    <input type="hidden" name="question_id" value={{question.id}}>
    <button type="submit">Submit</button>
  </form>
</body>
</html>

Code/jesse/django/AskCodeBusters/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Ask CodeBusters</title>
</head>
<body>
  {% include 'polls/_navbar.html' %}

  {% if request.user.is_anonymous %}
  
  Please login to create a poll.
  {% else %}
  <h2>Hello {{request.user}}</h2>
  {{request.user_is_anonymous}}
  <form action="{% url 'polls:generate_choices' %}" method="POST">
    {% csrf_token %}
    <input type="text" placeholder="Enter Poll:" name="question_text">
    <input type="number" step="1" min="2" max="8" name="num_choice">
    <button type="submit">Add Poll</button>
  </form>
  {% endif %}
  <h3>Current Polls</h3>
  {% for question in questions %}
    <h4>{{ question.question_text }}</h4>
    <blockquote>{{question.user}}</blockquote>
    <ul>
      {% for choice in question.choices.all %}
        <li><a href="{% url 'polls:vote' choice.id %}">{{ choice.choice_text }}</a></li>
      {% endfor %}
    </ul>
    
  {% endfor %}
</body>
</html>

Code/jesse/django/AskCodeBusters/polls/templates/polls/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  {% include 'polls/_navbar.html' %}
  <form action="{% url 'polls:login' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Username" required>
    <input type="password" name="password" placeholder="Password" required>
    <button type="submit">Login</button>
    <a href="{% url 'polls:signup' %}">or signup</a>
  </form>
</body>
</html>

Code/jesse/django/AskCodeBusters/polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{question.question_text}}</title>
</head>
<body>
  {% include 'polls/_navbar.html' %}
  {% for choice in question.choices.all %}
    <p>{{choice.choice_text}} -- {{choice.votes}}</p>
  {% endfor %}
  <a href="{% url 'polls:home' %}">Vote Again</a>
</body>
</html>

Code/jesse/django/AskCodeBusters/polls/templates/polls/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sign-up</title>
</head>
<body>
  {% include 'polls/_navbar.html' %}

  <form action="{% url 'polls:signup' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Username" required>
    <input type="password" name="password" placeholder="Password" required>
    <input type="email" name="email" placeholder="Email" required>
    <input type="text" name="first_name" placeholder="First Name">
    <input type="text" name="last_name" placeholder="Last Name">
    <button type="submit">Sign-Up</button>
  </form>
</body>
</html>

Code/jesse/django/AskCodeBusters/polls/templates/polls/user_polls.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{user.username}}</title>
</head>
<body>
  {% if user.questions.all %}
  Showing polls for {{user.username}}.
  {% endif %}
  {% for question in user.questions.all %}
    <h3>{{ question.question_text }}</h3>
    <ul>
      {% for choice in question.choices.all %}
        <li>{{choice.choice_text}}</li>
      {% endfor %}
    </ul>
  {% empty %}
    No polls created yet.
  {% endfor %}
</body>
</html>